/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/apple_watch_ultra_2.glb --types --shadows 
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-ultra-2-f33263c457664b43909200c5ed5e6fa2
Title: Apple Watch Ultra 2
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    LbodUHJUCGqowCz: THREE.Mesh
    BMKlRAQYzgiNCrq_1: THREE.Mesh
    joGEgikMuDmcVlT: THREE.Mesh
    ytGVVkppetlPrjk: THREE.Mesh
    bXoKVYbQhcORrRo: THREE.Mesh
    LMTUXYhSYYJrnsy_0: THREE.Mesh
    HoKUOQkmlXGGrun: THREE.Mesh
    LMTUXYhSYYJrnsy: THREE.Mesh
    niuesVpLyOylhzG: THREE.Mesh
    dAobUVRiwHRHUwW: THREE.Mesh
    odYscQETIRVJKxR: THREE.Mesh
    qHpopFXBXmHOUYS: THREE.Mesh
    AXTiAWNANGWNPZh: THREE.Mesh
    pYoTjWyHwknCsXs: THREE.Mesh
    GYKIDhUtSmfksAh: THREE.Mesh
    tZSTMNOYIPNFEiO: THREE.Mesh
    IIYcDhGuQelMSoT: THREE.Mesh
    jGEqmDFMbHJGHIM: THREE.Mesh
    EefvmwIVeXQqJgK: THREE.Mesh
    pPJyCszCvDGrLse: THREE.Mesh
    gkDXZCmXAkhmUzR: THREE.Mesh
    UNygooOJQBdvEQH: THREE.Mesh
    URfXVlSvtJbSCOD: THREE.Mesh
    OFYufNMwvtHmxdH: THREE.Mesh
    mcBIQkSNmBqhwzR: THREE.Mesh
    dEKwzvajmGpjRpl: THREE.Mesh
    iQrteZnlrWZpbxz: THREE.Mesh
    ggBokQJJgYcckom: THREE.Mesh
    SWRxiioprGlZKOq: THREE.Mesh
    AnKriXdRdkHvVgp: THREE.Mesh
    nKBIvEakrYhfdsQ: THREE.Mesh
    VqmyRLxQuilpALX: THREE.Mesh
    IYFwQnCDaiSiRdc: THREE.Mesh
    FiiGAhWFHdUxhDn: THREE.Mesh
    pVqLnJdxODmWtTg: THREE.Mesh
    vyDTdhAtbzsQFUf: THREE.Mesh
    fOvUJMAYMqVGOTV: THREE.Mesh
    ffjHNJzYIjDziJe: THREE.Mesh
    dGxaGtgSeaFVukl: THREE.Mesh
    YXUXfLDEwbvOPVY: THREE.Mesh
    jLHIkNOojYqBogV: THREE.Mesh
    OmcQxRYSzLYYjzi: THREE.Mesh
    HGmbyGfKBcsbZXU: THREE.Mesh
    EZmdWXCjqrUDeoX: THREE.Mesh
    KUPfCqZVKycFVaN: THREE.Mesh
    PiDhoxwwGLYiaUX_0: THREE.Mesh
    RJSoCQhkGkkzpXt_0: THREE.Mesh
    YufihILXVHVrDwt: THREE.Mesh
    kAITCUcjTiAaCrp: THREE.Mesh
    wKIPMqpyTsCHWIy: THREE.Mesh
    AGCoudWoaDmiMRH: THREE.Mesh
    NONHYSHLUQzoyez: THREE.Mesh
    nUikKFsvZdptvXF: THREE.Mesh
    VHnHbLOyhEXLvWA: THREE.Mesh
    DCiPNWQGULbWNNE: THREE.Mesh
  }
  materials: {
    PmrTDgoSkxCPUel: THREE.MeshStandardMaterial
    yKAKXxwHUkGVYpC: THREE.MeshStandardMaterial
    GXPSJdzybTrBefY: THREE.MeshStandardMaterial
    CdZJpyOXLDMygZg: THREE.MeshStandardMaterial
    AGtKlWnOInmqNQI: THREE.MeshStandardMaterial
    LMTUXYhSYYJrnsy_0: THREE.MeshStandardMaterial
    YtajTVWccmKRZBL: THREE.MeshStandardMaterial
    edhWAPEBZsqCLTg: THREE.MeshStandardMaterial
    GvXrALMIeaGmIJo: THREE.MeshStandardMaterial
    KjETpDnldvdbNBw: THREE.MeshStandardMaterial
    VJcIxaYCeMHzzAJ: THREE.MeshStandardMaterial
    vqobCvtAVyNLbeh: THREE.MeshStandardMaterial
    JlRKetQcktLwJwa: THREE.MeshStandardMaterial
    NfRpqTxrWQxoAIy: THREE.MeshStandardMaterial
    gYvxxOpBYwEcvOZ: THREE.MeshStandardMaterial
    ihcWbztBiuXfzKC: THREE.MeshStandardMaterial
    EbFYvXZFEOELnji: THREE.MeshStandardMaterial
    hSvQcziHKpXubDY: THREE.MeshStandardMaterial
    yXTwmSCvToGuMDP: THREE.MeshStandardMaterial
    VkUcBAhoopQFcky: THREE.MeshStandardMaterial
    IvaXKlaVZetAvuj: THREE.MeshStandardMaterial
    dSEglLtoqwjlQIP: THREE.MeshStandardMaterial
    IsuszdatyklnjoT: THREE.MeshStandardMaterial
    ICUREbcRKnCadKa: THREE.MeshStandardMaterial
    CevCCqOWPSfMvyq: THREE.MeshStandardMaterial
    boERCOkfaeYKPmb: THREE.MeshStandardMaterial
    troyYZUIqRYbiDX: THREE.MeshStandardMaterial
    ivgxAOQoWknkmNj: THREE.MeshStandardMaterial
    FsJfKVbzNLXJeBa: THREE.MeshStandardMaterial
    sTxeXXVKohXeDJU: THREE.MeshStandardMaterial
    lgIBGhMXHpTEcfq: THREE.MeshStandardMaterial
    JSFaTttTQosHtdR: THREE.MeshStandardMaterial
    edYkGGAdRWeopLP: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/apple_watch_ultra_2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.NONHYSHLUQzoyez.geometry} material={materials.JSFaTttTQosHtdR} />
        <mesh castShadow receiveShadow geometry={nodes.nUikKFsvZdptvXF.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.VHnHbLOyhEXLvWA.geometry} material={materials.edYkGGAdRWeopLP} />
        <mesh castShadow receiveShadow geometry={nodes.DCiPNWQGULbWNNE.geometry} material={materials.AGtKlWnOInmqNQI} />
        <mesh castShadow receiveShadow geometry={nodes.LbodUHJUCGqowCz.geometry} material={materials.PmrTDgoSkxCPUel} />
        <mesh castShadow receiveShadow geometry={nodes.BMKlRAQYzgiNCrq_1.geometry} material={materials.yKAKXxwHUkGVYpC} />
        <mesh castShadow receiveShadow geometry={nodes.joGEgikMuDmcVlT.geometry} material={materials.GXPSJdzybTrBefY} />
        <mesh castShadow receiveShadow geometry={nodes.ytGVVkppetlPrjk.geometry} material={materials.CdZJpyOXLDMygZg} />
        <mesh castShadow receiveShadow geometry={nodes.bXoKVYbQhcORrRo.geometry} material={materials.AGtKlWnOInmqNQI} />
        <mesh castShadow receiveShadow geometry={nodes.LMTUXYhSYYJrnsy_0.geometry} material={materials.LMTUXYhSYYJrnsy_0} />
        <mesh castShadow receiveShadow geometry={nodes.HoKUOQkmlXGGrun.geometry} material={materials.YtajTVWccmKRZBL} />
        <mesh castShadow receiveShadow geometry={nodes.LMTUXYhSYYJrnsy.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.niuesVpLyOylhzG.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.dAobUVRiwHRHUwW.geometry} material={materials.GvXrALMIeaGmIJo} />
        <mesh castShadow receiveShadow geometry={nodes.odYscQETIRVJKxR.geometry} material={materials.KjETpDnldvdbNBw} />
        <mesh castShadow receiveShadow geometry={nodes.qHpopFXBXmHOUYS.geometry} material={materials.VJcIxaYCeMHzzAJ} />
        <mesh castShadow receiveShadow geometry={nodes.AXTiAWNANGWNPZh.geometry} material={materials.vqobCvtAVyNLbeh} />
        <mesh castShadow receiveShadow geometry={nodes.pYoTjWyHwknCsXs.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.GYKIDhUtSmfksAh.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.tZSTMNOYIPNFEiO.geometry} material={materials.YtajTVWccmKRZBL} />
        <mesh castShadow receiveShadow geometry={nodes.IIYcDhGuQelMSoT.geometry} material={materials.JlRKetQcktLwJwa} />
        <mesh castShadow receiveShadow geometry={nodes.jGEqmDFMbHJGHIM.geometry} material={materials.NfRpqTxrWQxoAIy} />
        <mesh castShadow receiveShadow geometry={nodes.EefvmwIVeXQqJgK.geometry} material={materials.gYvxxOpBYwEcvOZ} />
        <mesh castShadow receiveShadow geometry={nodes.pPJyCszCvDGrLse.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.gkDXZCmXAkhmUzR.geometry} material={materials.gYvxxOpBYwEcvOZ} />
        <mesh castShadow receiveShadow geometry={nodes.UNygooOJQBdvEQH.geometry} material={materials.ihcWbztBiuXfzKC} />
        <mesh castShadow receiveShadow geometry={nodes.URfXVlSvtJbSCOD.geometry} material={materials.EbFYvXZFEOELnji} />
        <mesh castShadow receiveShadow geometry={nodes.OFYufNMwvtHmxdH.geometry} material={materials.hSvQcziHKpXubDY} />
        <mesh castShadow receiveShadow geometry={nodes.mcBIQkSNmBqhwzR.geometry} material={materials.CdZJpyOXLDMygZg} />
        <mesh castShadow receiveShadow geometry={nodes.dEKwzvajmGpjRpl.geometry} material={materials.yXTwmSCvToGuMDP} />
        <mesh castShadow receiveShadow geometry={nodes.iQrteZnlrWZpbxz.geometry} material={materials.VkUcBAhoopQFcky} />
        <mesh castShadow receiveShadow geometry={nodes.ggBokQJJgYcckom.geometry} material={materials.IvaXKlaVZetAvuj} />
        <mesh castShadow receiveShadow geometry={nodes.SWRxiioprGlZKOq.geometry} material={materials.dSEglLtoqwjlQIP} />
        <mesh castShadow receiveShadow geometry={nodes.AnKriXdRdkHvVgp.geometry} material={materials.IsuszdatyklnjoT} />
        <mesh castShadow receiveShadow geometry={nodes.nKBIvEakrYhfdsQ.geometry} material={materials.ICUREbcRKnCadKa} />
        <mesh castShadow receiveShadow geometry={nodes.VqmyRLxQuilpALX.geometry} material={materials.CevCCqOWPSfMvyq} />
        <mesh castShadow receiveShadow geometry={nodes.IYFwQnCDaiSiRdc.geometry} material={materials.AGtKlWnOInmqNQI} />
        <mesh castShadow receiveShadow geometry={nodes.FiiGAhWFHdUxhDn.geometry} material={materials.boERCOkfaeYKPmb} />
        <mesh castShadow receiveShadow geometry={nodes.pVqLnJdxODmWtTg.geometry} material={materials.troyYZUIqRYbiDX} />
        <mesh castShadow receiveShadow geometry={nodes.vyDTdhAtbzsQFUf.geometry} material={materials.ivgxAOQoWknkmNj} />
        <mesh castShadow receiveShadow geometry={nodes.fOvUJMAYMqVGOTV.geometry} material={materials.FsJfKVbzNLXJeBa} />
        <mesh castShadow receiveShadow geometry={nodes.ffjHNJzYIjDziJe.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.dGxaGtgSeaFVukl.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.YXUXfLDEwbvOPVY.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.jLHIkNOojYqBogV.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.OmcQxRYSzLYYjzi.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.HGmbyGfKBcsbZXU.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.EZmdWXCjqrUDeoX.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh castShadow receiveShadow geometry={nodes.KUPfCqZVKycFVaN.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh castShadow receiveShadow geometry={nodes.PiDhoxwwGLYiaUX_0.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.RJSoCQhkGkkzpXt_0.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh castShadow receiveShadow geometry={nodes.YufihILXVHVrDwt.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh castShadow receiveShadow geometry={nodes.kAITCUcjTiAaCrp.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh castShadow receiveShadow geometry={nodes.wKIPMqpyTsCHWIy.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh castShadow receiveShadow geometry={nodes.AGCoudWoaDmiMRH.geometry} material={materials.edhWAPEBZsqCLTg} />
      </group>
    </group>
  )
}

useGLTF.preload('/apple_watch_ultra_2.glb')
